apiVersion: v1
kind: Secret
metadata:
  name: invoice-mariadb
  namespace: xl-demo
  labels:
    app: invoice-mariadb
type: Opaque
data:
  mariadb-root-password: d3dsY20zNjU=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-mariadb
  namespace: xl-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-mariadb
  template:
    metadata:
      labels:
        app: invoice-mariadb
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: mariadb
          image: mariadb:10.4.5
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: invoice-mariadb
                  key: mariadb-root-password
            - name: MYSQL_DATABASE
              value: invoice
          #        command:
          #        - mysqld
          #        - --lower_case_table_names=1
          #        - --skip-ssl
          #        - --character_set_server=utf8mb4
          #        - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-mariadb
  namespace: xl-demo
spec:
  selector:
    app: invoice-mariadb
  ports:
    - port: 3306
